### ISSUE TITLE
Let's encrypt certificate ssl folder not found

### ISSUE THREAD

**Issue by Moimemeici** [hardware/mailserver#345] opened 2019-01-02 09:02 UTC
#### Classification
* [X] Question

#### Reproducibility
* [X] Always

#### Docker information
```
EPOSITORY            TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
hardware/mailserver   1.1-stable          sha256:7ca1260cdf1118945928acd58c502d6ae1c936b41a4f1a6d5ff99cfbff1acd90   805f0b1959ab        2 months ago        380MB
hardware/mailserver   <none>              sha256:b1ebc44176c548dc8386e1a14a5e676144cb4a4cc79f89849ce60bcbff3bdbdb   c43e799e6bf9        2 months ago        379MB
hardware/mailserver   <none>              sha256:e56eb759a61b483924708c1eb5fb81d5aa32191ef420c197e7313cc1b0137364   a4f7ef1fb6d3        2 months ago        379MB
hardware/mailserver   <none>              sha256:841d78c2f7206e2cd8d5ec87774f4efc9614784fc7822cc41b5e62a8dbafebb3   34f98b9c0aef        3 months ago        379MB
hardware/mailserver   <none>              sha256:293e2a37d49ed7c2ccba12ab38e88e63057d46598832f4eaa0b29b745bee47c5   66477618802b        5 months ago        364MB

```

#### Description
Your fantastics container don't see my poor let's encrypt ssl folder.
I use docker-compose v 2.1
i'm using nginx.
just suddenly stop work correctly.

#### Debugging information
```
[INFO] Traefik SSL certificates not used
[INFO] No Let's encrypt live directory found
[INFO] Using /var/mail/ssl/selfsigned/ folder
[INFO] No SSL certificates found, generating a new selfsigned certificate
Generating a 4096 bit RSA private key
........................................................................................................++
...............................................++
writing new private key to '/var/mail/ssl/selfsigned/privkey.pem'

```

#### Configuration (docker-compose.yml, traefik.toml...etc)

  mailserver:
    image: hardware/mailserver:1.1-stable
    container_name: mailserver
    domainname: mail.domain.tld                # Mail server A/MX/FQDN & reverse PTR = mail.domain.tld.
    hostname: mail
    # restart: always
    # extra_hosts:                          - Required for external database (on other server or for local databases on host without docker)
    #  - "mariadb:xx.xx.xx.xx"              - Replace with IP address of MariaDB server
    #  - "redis:xx.xx.xx.xx"                - Replace with IP address of Redis server
.......
    environment:
.......
    volumes:
......
      - /etc/letsencrypt/:/etc/letsencrypt/
 ......
    depends_on:
      - mariadb
      - redis

**Comment by navossoc** [comment] 2019-01-02 10:56
Try to run on the host and inside the container
```
ls -l /etc/letsencrypt/
```

Check if you are mounting the right folder content.
https://github.com/hardware/mailserver#custom-certificates

There is a folder named "live" and another one with your domain name.

```
/etc/letsencrypt# ls -l
total 8
drwxr-xr-x 2 root root 4096 Dec 19 08:41 acme
drwxr-xr-x 3 root root 4096 Dec 19 08:41 live

/etc/letsencrypt/live# ls -l
total 4
drwxr-xr-x 2 root root 4096 Dec 19 08:41 yourdomain.com

/etc/letsencrypt/live/yourdomain.com# ls -l
total 16
-rw-r--r-- 1 root root 2339 Dec 19 08:41 cert.pem
-rw-r--r-- 1 root root 1647 Dec 19 08:41 chain.pem
-rw------- 1 root root 3986 Dec 19 08:41 fullchain.pem
-rw------- 1 root root 3243 Dec 19 08:41 privkey.pem
```

**Comment by Moimemeici** [comment] 2019-01-02 14:01
On host:

> 
> ls -l /etc/letsencrypt/
> total 44
> drwx------  5 991 991  4096 sept.  4 16:05 accounts
> drwx------ 22 991 991  4096 oct.  24 06:38 archive
> drwx------  2 991 991 12288 déc.  27 12:51 csr
> drwx------  2 991 991 12288 déc.  27 12:51 keys
> drwx------ 21 991 991  4096 oct.  24 06:38 live
> drwx------  2 991 991  4096 déc.  27 12:51 renewal
> drwx------  5 991 991  4096 nov.   2  2017 renewal-hooks
> 
> 
> ls -l /etc/letsencrypt/live/
> 
> total 76
> drwx------ 2 991 991 4096 nov.  10 18:03 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:03 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:04 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:05 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 déc.   4 18:34 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 juil.  5 09:54 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 déc.   4 18:35 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 déc.  27 12:51 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:04 lucy.xxxxxxxxxxxxx.fr
> drwx------ 2 991 991 4096 nov.  10 18:05 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:04 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:04 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 déc.   4 18:35 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:04 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:03 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:05 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:03 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:03 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:05 xxxxxxxxxxxxx
> 
> ls -l /etc/letsencrypt/live/lucy.xxxxxxxxxxxxx.fr/
> total 0
> lrwxrwxrwx 1 991 991 39 nov.  10 18:04 cert.pem -> ../../archive/lucy.xxxxxxxxxxxxx.fr/cert14.pem
> lrwxrwxrwx 1 991 991 40 nov.  10 18:04 chain.pem -> ../../archive/lucy.xxxxxxxxxxxxx.fr/chain14.pem
> lrwxrwxrwx 1 991 991 44 nov.  10 18:04 fullchain.pem -> ../../archive/lucy.xxxxxxxxxxxxx.fr/fullchain14.pem
> lrwxrwxrwx 1 991 991 42 nov.  10 18:04 privkey.pem -> ../../archive/lucy.xxxxxxxxxxxxx.fr/privkey14.pem

On Container:

> 
>  ls -l /etc/letsencrypt/
> total 44
> drwx------  5 991 991  4096 Sep  4 16:05 accounts
> drwx------ 22 991 991  4096 Oct 24 06:38 archive
> drwx------  2 991 991 12288 Dec 27 12:51 csr
> drwx------  2 991 991 12288 Dec 27 12:51 keys
> drwx------ 21 991 991  4096 Oct 24 06:38 live
> drwx------  2 991 991  4096 Dec 27 12:51 renewal
> drwx------  5 991 991  4096 Nov  2  2017 renewal-hooks

> ls -l /etc/letsencrypt/live/
> 
> total 76
> drwx------ 2 991 991 4096 nov.  10 18:03 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:03 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:04 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:05 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 déc.   4 18:34 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 juil.  5 09:54 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 déc.   4 18:35 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 déc.  27 12:51 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:04 lucy.xxxxxxxxxxxxx.fr
> drwx------ 2 991 991 4096 nov.  10 18:05 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:04 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:04 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 déc.   4 18:35 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:04 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:03 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:05 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:03 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:03 xxxxxxxxxxxxx
> drwx------ 2 991 991 4096 nov.  10 18:05 xxxxxxxxxxxxx
> 
> ls -l /etc/letsencrypt/live/lucy.xxxxxxxxxxxxx.fr/
> total 0
> lrwxrwxrwx 1 991 991 39 nov.  10 18:04 cert.pem -> ../../archive/lucy.xxxxxxxxxxxxx.fr/cert14.pem
> lrwxrwxrwx 1 991 991 40 nov.  10 18:04 chain.pem -> ../../archive/lucy.xxxxxxxxxxxxx.fr/chain14.pem
> lrwxrwxrwx 1 991 991 44 nov.  10 18:04 fullchain.pem -> ../../archive/lucy.xxxxxxxxxxxxx.fr/fullchain14.pem
> lrwxrwxrwx 1 991 991 42 nov.  10 18:04 privkey.pem -> ../../archive/lucy.xxxxxxxxxxxxx.fr/privkey14.pem

**Comment by navossoc** [comment] 2019-01-02 14:42
Maybe the problem is the symlink?

Have you tried to `cat /etc/letsencrypt/live/yourdomain.com/cert.pem` (host/container) to see if they are resolving correctly?

I'm not sure how docker handles symlinks on bind mounted folders. Specially if there is a "renew"(lets encrypt) and the symlinks get updated.

Have you tried to restart the container, just to rule out this possibility (symlinks not update because of the renew)?

[]'s

**Comment by Moimemeici** [comment] 2019-01-02 19:46
all is good ... 
maybe i'am going delete my certs and i make new ...

**Comment by Moimemeici** [comment] 2019-01-03 03:56
i don't understand this problem

![certs_1](https://user-images.githubusercontent.com/19207283/50623227-d858bc00-0f13-11e9-9e50-767388e7d509.JPG)
![certs_2](https://user-images.githubusercontent.com/19207283/50623228-d858bc00-0f13-11e9-88ca-e4c6a3f05920.JPG)
![certs_3](https://user-images.githubusercontent.com/19207283/50623229-d858bc00-0f13-11e9-9869-211dbf8b275c.JPG)
![certs_4](https://user-images.githubusercontent.com/19207283/50623230-d858bc00-0f13-11e9-9f00-8d3411fcb1ff.JPG)

**Comment by Moimemeici** [comment] 2019-01-04 06:43
Hello, 
i use this:

> docker exec -ti mailserver bash
> # hostname --fqdn

I see the result is not correct

> lucy.lucy.xxxxxx.fr

i delete the container and all is good now.
why hostname is not good i don't know

**Closed** 2019-01-04 06:43 UTC
